#!/bin/bash

# Variáveis
TELEGRAM_API_KEY="TOKEN TELEGRAM"
TELEGRAM_CHAT_ID="ID DO CHAT"
NOME="$(hostname)"

# Diretórios de backup
SOURCE_DIRS=(
        "/etc/asterisk"
        "/var/www/html/"
        "/var/lib/asterisk/agi-bin"
        "/var/lib/asterisk/sounds/ura-inteligente"
        "/etc/backup"
)

BACKUP_DIR="/tmp"

# Nome do arquivo de backup
BACKUP_FILE="backup_${NOME}_$(date +"%Y%m%d%H%M%S").tar.gz"
PERMISSIONS_FILE="permissions_${NOME}_$(date +"%Y%m%d%H%M%S").txt"
MYSQL_USER="USUARIO"
MYSQL_PASSWORD="SENHA"
MYSQL_DATABASES=("asterisk" "call_center")

# Cria um diretório temporário para armazenar os arquivos e permissões
TEMP_DIR=$(mktemp -d)

# Copia os arquivos para o diretório temporário, mantendo a estrutura de diretórios
for SOURCE_DIR in "${SOURCE_DIRS[@]}"; do
    DEST_DIR="$TEMP_DIR$(dirname "$SOURCE_DIR")"
    mkdir -p "$DEST_DIR"
    cp -a "$SOURCE_DIR" "$DEST_DIR"
done

# Faz o backup dos bancos de dados MySQL
for DATABASE in "${MYSQL_DATABASES[@]}"; do
    mysqldump -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$DATABASE" > "$TEMP_DIR/${DATABASE}.sql"
    if [ $? -eq 0 ]; then
        echo "Backup do banco de dados $DATABASE realizado com sucesso."
    else
        echo "Erro ao fazer o backup do banco de dados $DATABASE."
    fi
done

# Coleta as permissões dos arquivos e salva em um arquivo de texto
find "$TEMP_DIR" -type f -exec stat -c "chmod %a %n" {} \; > "$TEMP_DIR/$PERMISSIONS_FILE"

# Compacta os arquivos e o arquivo de permissões
tar -czf "$BACKUP_DIR/$BACKUP_FILE" -C "$TEMP_DIR" .

# Envia o arquivo para o Telegram
curl -F "chat_id=$TELEGRAM_CHAT_ID" \
     -F "document=@$BACKUP_DIR/$BACKUP_FILE" \
     "https://api.telegram.org/bot$TELEGRAM_API_KEY/sendDocument"

# Verifica se o envio foi bem-sucedido
if [ $? -eq 0 ]; then
    echo "Backup realizado e enviado para o Telegram com sucesso."
else
    echo "Erro ao enviar o backup para o Telegram."
fi

# Remove o diretório temporário
rm -rf "$TEMP_DIR"
rm -rf "$BACKUP_DIR/$BACKUP_FILE"
